spring.application.name=todo
server.port=3000
#DB
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:todo_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=h2db
spring.datasource.password=h2db

#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

